// <auto-generated />
using System;
using ECBS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECBS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EcbsDbContext))]
    [Migration("20260710185540_ClientManagementWriteModel")]
    partial class ClientManagementWriteModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECBS.Domain.ClientManagement.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("json");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectWorkflowDraftId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("RequestedReportTypes")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId", "CreatedAtUtc");

                    b.ToTable("report_requests", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ClientType")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LogoStorageUri")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("PrimaryContactName")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PrimaryContactTitle")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Data.TelemetryInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("IntervalStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("KilovoltAmps")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("KilowattHours")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Kilowatts")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PowerFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "DeviceId", "IntervalStartUtc")
                        .IsUnique();

                    b.ToTable("telemetry_intervals", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("CommissionedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "Name");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("LastCommunicatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "IsMain");

                    b.HasIndex("TenantId", "ProjectId", "SerialNumber")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Documents.DocumentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FileName")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectWorkflowDraftId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("StorageUri")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId", "ProjectId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Integration.SourceMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EcbsEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EcbsEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("SourceDatabase")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("SyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EcbsEntityType", "EcbsEntityId", "SourceSystem");

                    b.ToTable("source_mappings", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ProjectType")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateOnly?>("TargetCompletionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId", "Name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Projects.ProjectWorkflowDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DraftName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("json");

                    b.Property<string>("ProjectManager")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProjectType")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("RequiredDocumentStatus")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateOnly?>("TargetCompletionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId", "CreatedAtUtc");

                    b.ToTable("project_workflow_drafts", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Reports.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("StorageUri")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "ReportType", "GeneratedAtUtc");

                    b.ToTable("report_runs", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("SiteNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Status")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Utility")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ClientId", "Name");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("ECBS.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
