# Declare an "upstream", i.e. a server that Nginx assumes is listening for requests,
# so that it can proxy traffic to it.  This is our Sails server.
upstream sails {
    server 127.0.0.1:8081;
    keepalive 256;
}

# Listen for all requests on port 8082 and redirect them to https://.
# In order for this to work, iptables rules must be added that redirect
# traffic from some specific port on the machine (in our case 81) to
# internal port 8082.
server {
    listen 8082;
    rewrite ^ https://$host$uri permanent;
}

# Listen for all requests on port 8080 and proxy them to the Sails server.
# By default, Elastic Beanstalk sets up iptables rules to forward all
# traffic on port 80 of the machine to internal port 8080.
server {
    listen 8080 proxy_protocol;

    location / {
        proxy_pass  http://sails;
        proxy_set_header   Connection "";
        proxy_http_version 1.1;
        proxy_set_header        Upgrade           $http_upgrade;
        proxy_set_header        Connection        "upgrade";
        proxy_set_header        Host              $host;
        proxy_set_header        X-Real-IP         $remote_addr;
        proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
        # Using proxy protocol means that $scheme always just shows HTTP, so in order for
        # secure cookies to work we'll hard-code this to https and use the separate port
        # for HTTP traffic, funneled to internal port 8082.
        proxy_set_header        X-Forwarded-Proto "https";
    }

gzip on;
gzip_comp_level 4;
gzip_types text/html text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;


}


