module.exports = sails.config.constants.buildCreateAction('switch', {
  before: function(inputs, proceed) {

    Switch.find({deviceId: inputs.valuesToSet.deviceId.trim(), isDeleted: false}).exec(function(err, switches) {
      if (err) { return proceed(err); }
      if (switches.length) {
        var conflictErr = new Error('A switch already exists with this device ID');
        conflictErr.exit='conflict';
        return proceed(conflictErr);
      }
      return proceed();
    });

  },

  after: function(newSwitch, exits) {

    // See if there is any PiBoard recorded with the new Switch's Pi-board serial #.
    PiBoard.findOne({
      deviceId: newSwitch.deviceId
    }).exec(function(err, piBoard) {
      if (err) {
        return exits.error(err);
      }

      // If not, then the switch is not online yet (this should be the norm), so we'll just return
      // through the `success` exit generated by `buildCreateAction`.
      if (!piBoard) {
        return exits.success({
          response: {
            id: newSwitch.id
          }
        });
      }

      // If so, first update the new switch with the PiBoard's mesh ID.
      Switch.update({
        id: newSwitch.id
      }, {
        meshId: piBoard.meshId
      }).exec(function(err) {
        if (err) {
          return exits.error(err);
        }
        if (newSwitch.deviceType == 2) {
          ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'today', valueType: 'kwh', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
          ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'today', valueType: 'totalCost', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
           ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'week', valueType: 'totalCost', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
           ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'month', valueType: 'totalCost', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
           ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'year', valueType: 'totalCost', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
           ReportData.create({type: 'scheduler', typeId: newSwitch.id, project: newSwitch.project, period: 'allTime', valueType: 'totalCost', value: 0}).meta({fetch: true}).exec(function(err, updatedSwitch){
            if (err) {
              console.log('[' + Moment().format() + '] upload savings detail for meter error ' + newSwitch.id);
            }
          });
        }
        return exits.success({
          response: {
            id: newSwitch.id
          }
        });
      });

    });
  }
});
