module.exports = sails.config.constants.buildUpdateAction('switch', {

  before: function(inputs, proceed) {
    if (inputs.valuesToSet.deviceId){
      Switch.find({deviceId: inputs.valuesToSet.deviceId.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, switches) {
        if (err) {
          return proceed(err);
        }
        if (switches.length) {
          var conflictErr = new Error('A switch already exists with this device ID');
          conflictErr.exit = 'conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    } else if (inputs.valuesToSet.name){
      Switch.find({deviceId: inputs.valuesToSet.name.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, switches) {
        if (err) {
          return proceed(err);
        }
        if (switches.length) {
          var conflictErr = new Error('A switch already exists with this device ID');
          conflictErr.exit = 'conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    }

  },

  after: function(updatedSwitch, exits) {

    // See if there is any PiBoard recorded with the new Switch's Pi-board serial #.
    PiBoard.findOne({
      deviceId: updatedSwitch.deviceId
    }).exec(function(err, piBoard) {
      if (err) {
        return exits.error(err);
      }

      // If not, then the switch is not online yet (this should be the norm), so we'll just return
      // through the `success` exit generated by `buildCreateAction`.
      if (!piBoard) {
        return exits.success({
          response: {
            id: updatedSwitch.id
          }
        });
      }

      // If so, first update the new switch with the PiBoard's mesh ID.
      Switch.update({
        id: updatedSwitch.id
      }, {
        meshId: piBoard.meshId
      }).exec(function(err) {
        if (err) {
          return exits.error(err);
        }
        return exits.success({
          response: {
            id: updatedSwitch.id
          }
        });
      });

    });
  },

  whitelist: [
    'name',
    'deviceId'
  ]
});
