module.exports = sails.config.constants.buildCreateAction('repeater', {

  before: function(inputs, proceed) {

    Repeater.find({deviceId: inputs.valuesToSet.deviceId.trim(), isDeleted: false}).exec(function(err, repeaters) {
      if (err) { return proceed(err); }
      if (repeaters.length) {
        var conflictErr = new Error('A repeater already exists with this device ID');
        conflictErr.exit='conflict';
        return proceed(conflictErr);
      }
      return proceed();
    });

  },

  after: function(newRepeater, exits) {

    // See if there is any PiBoard recorded with the new Repeater's Pi-board serial #.
    PiBoard.findOne({
      deviceId: newRepeater.deviceId
    }).exec(function(err, piBoard) {
      if (err) {
        return exits.error(err);
      }

      // If not, then the repeater is not online yet (this should be the norm), so we'll just return
      // through the `success` exit generated by `buildCreateAction`.
      if (!piBoard) {
        return exits.success({
          response: {
            id: newRepeater.id
          }
        });
      }

      // If so, first update the new repeater with the PiBoard's mesh ID.
      Repeater.update({
        id: newRepeater.id
      }, {
        meshId: piBoard.meshId
      }).exec(function(err) {
        if (err) {
          return exits.error(err);
        }
        return exits.success({
          response: {
            id: newRepeater.id
          }
        });
      });

    });
  }
});
