module.exports = sails.config.constants.buildUpdateAction('repeater', {

  before: function(inputs, proceed) {

    if (inputs.valuesToSet.deviceId){
      Repeater.find({deviceId: inputs.valuesToSet.deviceId.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, repeaters) {
        if (err) { return proceed(err); }
        if (repeaters.length) {
          var conflictErr = new Error('A repeater already exists with this device ID');
          conflictErr.exit='conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    } else if (inputs.valuesToSet.name){
      Repeater.find({deviceId: inputs.valuesToSet.name.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, repeaters) {
        if (err) { return proceed(err); }
        if (repeaters.length) {
          var conflictErr = new Error('A repeater already exists with this device ID');
          conflictErr.exit='conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    }

  },

  after: function(updatedRepeater, exits) {

    // See if there is any PiBoard recorded with the new Repeater's Pi-board serial #.
    PiBoard.findOne({
      deviceId: updatedRepeater.deviceId
    }).exec(function(err, piBoard) {
      if (err) {
        return exits.error(err);
      }

      // If not, then the repeater is not online yet (this should be the norm), so we'll just return
      // through the `success` exit generated by `buildCreateAction`.
      if (!piBoard) {
        return exits.success({
          response: {
            id: updatedRepeater.id
          }
        });
      }

      // If so, first update the new repeater with the PiBoard's mesh ID.
      Repeater.update({
        id: updatedRepeater.id
      }, {
        meshId: piBoard.meshId
      }).exec(function(err) {
        if (err) {
          return exits.error(err);
        }
        return exits.success({
          response: {
            id: updatedRepeater.id
          }
        });
      });

    });
  }
});

