"""Meter model - api/models/Meter.js"""
from app.extensions import db
from app.models.base import BaseModel


class Meter(BaseModel):
    __tablename__ = "meter"

    name = db.Column(db.String(255))
    deviceId = db.Column(db.String(255), nullable=False)
    meshId = db.Column(db.String(255))
    meshIp = db.Column(db.String(255), nullable=True)
    meterSerialNumber = db.Column(db.String(255))
    gateway = db.Column(db.String(255), nullable=True)
    lastTimestamp = db.Column(db.Float, nullable=True)
    project = db.Column(db.Integer, db.ForeignKey("project.id"))
    lastCommunicatedAt = db.Column(db.Float)
    meshLastCommunicatedAt = db.Column(db.Float)
    isDeleted = db.Column(db.Boolean, default=False)
    isReporting = db.Column(db.Boolean, default=True)
    lastL1Volt = db.Column(db.Float)
    lastL1Amp = db.Column(db.Float)
    lastL1Kw = db.Column(db.Float)
    lastL1Kva = db.Column(db.Float)
    lastL1Pf = db.Column(db.Float)
    lastL1Kvar = db.Column(db.Float)
    lastL2Volt = db.Column(db.Float)
    lastL2Amp = db.Column(db.Float)
    lastL2Kw = db.Column(db.Float)
    lastL2Kva = db.Column(db.Float)
    lastL2Pf = db.Column(db.Float)
    lastL2Kvar = db.Column(db.Float)
    lastL3Volt = db.Column(db.Float)
    lastL3Amp = db.Column(db.Float)
    lastL3Kw = db.Column(db.Float)
    lastL3Kva = db.Column(db.Float)
    lastL3Pf = db.Column(db.Float)
    lastL3Kvar = db.Column(db.Float)
    lastTotalVolt = db.Column(db.Float)
    lastTotalAmp = db.Column(db.Float)
    lastTotalKw = db.Column(db.Float)
    lastTotalKva = db.Column(db.Float)
    lastTotalPf = db.Column(db.Float)
    lastTotalKvar = db.Column(db.Float)
    lastTotalTHD = db.Column(db.Float, nullable=True)
    peakTime = db.Column(db.String(255), nullable=True)
    isSub = db.Column(db.Integer, nullable=True)
    isMain = db.Column(db.Integer, nullable=True)
    isFilter = db.Column(db.Integer, nullable=True)
    multiplier = db.Column(db.Float, nullable=True)
    lastOutputAmp = db.Column(db.Float, nullable=True)
    monthKwh = db.Column(db.Float, default=0)
    weekKwh = db.Column(db.Float, default=0)
    todayKwh = db.Column(db.Float, default=0)
    lastMonthKwh = db.Column(db.Float, default=0)
    lastKwh = db.Column(db.Float, default=0)
    avg15MinuteKva = db.Column(db.Float, default=0)
    monthPeak = db.Column(db.Float, default=0)
    lastMonthPeak = db.Column(db.Float, default=0)
    lastMonthSavings = db.Column(db.Float, default=0)
    lastMonthBudget = db.Column(db.Float, default=0)
    yearSavings = db.Column(db.Float, default=0)
    lastYearSavings = db.Column(db.Float, default=0)
    projectSavings = db.Column(db.Float, default=0)
    monthI2RLoss = db.Column(db.Float, default=0)
    lastMonthI2RLoss = db.Column(db.Float, default=0)
    yearI2RLoss = db.Column(db.Float, default=0)
    lastYearI2RLoss = db.Column(db.Float, default=0)
    projectI2RLoss = db.Column(db.Float, default=0)
    todayI2RLoss = db.Column(db.Float, default=0)
    weekI2RLoss = db.Column(db.Float, default=0)
    kwhSavings = db.Column(db.Float, default=0)
    kwPeakSavings = db.Column(db.Float, default=0)
