"""
Phase 13: Synerex Royalty Engine™ model

Spec: ECBS OS v4 §41, §7, Appendix B-25

One row per (oem_org_id, period) representing a monthly royalty calculation.
Calculated by the royalty engine from active licensed meter counts and
the OEM's contracted royalty rate.

Table: royalties
"""
from app.extensions import db
from app.models.base import BaseModel


# Royalty status constants
ROYALTY_STATUS_PENDING  = "pending"    # calculated but not yet invoiced
ROYALTY_STATUS_INVOICED = "invoiced"   # invoice generated
ROYALTY_STATUS_PAID     = "paid"       # payment confirmed
ROYALTY_STATUS_WAIVED   = "waived"     # explicitly waived by Synerex Admin


class Royalty(BaseModel):
    """
    Monthly royalty record for one OEM.

    Spec: ECBS OS v4 §41, §7 "Royalty Management™"
    Appendix B-25: royalties table

    Inputs (per §7.2):
      - Active Licensed Meters  → licensed_meters
      - Revenue                 → revenue  (OEM's collected revenue for the period)
      - Contract Terms          → royalty_rate (OEM's contracted rate)
      - Royalty Rate            → royalty_due = licensed_meters × meter_fee OR revenue × royalty_rate

    Outputs (per §7.3):
      Monthly, Quarterly, Annual (aggregated at query time from monthly rows)
    """
    __tablename__ = "royalties"

    # ── Scope ─────────────────────────────────────────────────────────────────
    oem_org_id       = db.Column(db.String(255), nullable=False, index=True)
    # period = "YYYY-MM" e.g. "2025-05"
    period           = db.Column(db.String(7),   nullable=False, index=True)

    # ── Inputs ────────────────────────────────────────────────────────────────
    licensed_meters  = db.Column(db.Integer, nullable=False, default=0)
    active_meters    = db.Column(db.Integer, nullable=False, default=0)

    # Revenue = total monthly revenue generated by the OEM's active meters
    # Populated from project / service_plan data if available; else NULL
    revenue          = db.Column(db.Float, nullable=True)

    # Rate used for this calculation (snapshot at calculation time)
    royalty_rate     = db.Column(db.Float, nullable=True)   # e.g. 0.08 = 8% of revenue
    # Per-meter fee alternative (used if revenue is not tracked)
    meter_fee        = db.Column(db.Float, nullable=True)   # e.g. 15.00 per active meter/month

    # ── Outputs ───────────────────────────────────────────────────────────────
    royalty_due      = db.Column(db.Float, nullable=False, default=0.0)

    # ── Status ────────────────────────────────────────────────────────────────
    status           = db.Column(db.String(20), nullable=False,
                                 default=ROYALTY_STATUS_PENDING, index=True)

    # ── Audit fields ──────────────────────────────────────────────────────────
    calculated_at    = db.Column(db.BigInteger, nullable=True)
    calculated_by    = db.Column(db.Integer,    nullable=True)   # user.id
    paid_at          = db.Column(db.BigInteger, nullable=True)
    paid_by          = db.Column(db.Integer,    nullable=True)
    invoice_ref      = db.Column(db.String(255), nullable=True)
    notes            = db.Column(db.Text,        nullable=True)

    __table_args__ = (
        db.UniqueConstraint("oem_org_id", "period", name="uq_royalty_oem_period"),
        db.Index("ix_royalties_status",  "status"),
        db.Index("ix_royalties_period",  "period"),
    )
