"""
Utility Intelligence™ models — Phase 10: uBillTracker™ + uBillForecast™

Spec: ECBS OS v4 §18, §65–66, Figure A-10, Appendix B-14

Three tables:
  utility_accounts  — one per utility account / meter number at a site
  utility_bills     — one row per month per account (actual uploaded bills)
  utility_forecasts — one row per forecast period per project
"""
from app.extensions import db
from app.models.base import BaseModel


# ── Utility Account ───────────────────────────────────────────────────────────

class UtilityAccount(BaseModel):
    """
    One record per utility account (meter number or service account).
    A site can have multiple accounts (e.g. main service + separately-metered tenant).

    spec: GET /api/utility/accounts
    """
    __tablename__ = "utility_accounts"

    project_id     = db.Column(db.Integer, db.ForeignKey("project.id"),
                               nullable=False, index=True)
    site_id        = db.Column(db.Integer, db.ForeignKey("site.id"),
                               nullable=True, index=True)

    account_number = db.Column(db.String(100), nullable=True)   # utility account #
    meter_number   = db.Column(db.String(100), nullable=True)   # utility meter #
    utility_name   = db.Column(db.String(255), nullable=True)   # e.g. "Entergy Louisiana"
    tariff_code    = db.Column(db.String(100), nullable=True)   # rate schedule code
    service_address= db.Column(db.String(500), nullable=True)
    is_primary     = db.Column(db.Boolean, default=True)        # primary service account
    notes          = db.Column(db.Text, nullable=True)
    isDeleted      = db.Column(db.Boolean, default=False)

    __table_args__ = (
        db.UniqueConstraint(
            "project_id", "account_number",
            name="uq_utility_account_project_acct",
        ),
    )


# ── Utility Bill ──────────────────────────────────────────────────────────────

class UtilityBill(BaseModel):
    """
    One row per billing period (typically monthly) per utility account.
    Populated by manual upload or API import.

    spec: POST /api/utility/bills/upload, GET /api/utility/bills
    DB schema: Appendix B-14
    """
    __tablename__ = "utility_bills"

    project_id     = db.Column(db.Integer, db.ForeignKey("project.id"),
                               nullable=False, index=True)
    site_id        = db.Column(db.Integer, db.ForeignKey("site.id"),
                               nullable=True,  index=True)
    account_id     = db.Column(db.Integer, db.ForeignKey("utility_accounts.id"),
                               nullable=True,  index=True)

    # Billing period — stored as YYYY-MM string (e.g. "2025-04")
    bill_month     = db.Column(db.String(7),  nullable=False, index=True)
    bill_date      = db.Column(db.String(20), nullable=True)   # actual bill date
    due_date       = db.Column(db.String(20), nullable=True)

    # Usage (spec B-14)
    energy_kwh     = db.Column(db.Float, nullable=True)   # total kWh consumed
    demand_kw      = db.Column(db.Float, nullable=True)   # peak demand kW (billable)
    demand_kva     = db.Column(db.Float, nullable=True)   # kVA demand if billed on kVA
    power_factor   = db.Column(db.Float, nullable=True)   # avg PF for the period

    # Cost breakdown (spec B-14)
    energy_cost    = db.Column(db.Float, nullable=True)   # $
    demand_cost    = db.Column(db.Float, nullable=True)   # $
    taxes          = db.Column(db.Float, nullable=True)   # $
    fees           = db.Column(db.Float, nullable=True)   # $ (fixed charges, customer charge)
    total_cost     = db.Column(db.Float, nullable=True)   # $ — energy + demand + taxes + fees

    # Derived rate (computed at upload or import time)
    effective_energy_rate = db.Column(db.Float, nullable=True)  # $/kWh (energy_cost / energy_kwh)
    effective_demand_rate = db.Column(db.Float, nullable=True)  # $/kW (demand_cost / demand_kw)

    # Upload metadata
    uploaded_at    = db.Column(db.BigInteger, nullable=True, index=True)
    uploaded_by    = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=True)
    source         = db.Column(db.String(50), nullable=True)  # "manual" | "api" | "ocr"
    notes          = db.Column(db.Text, nullable=True)
    is_estimated   = db.Column(db.Boolean, default=False)  # True if bill is estimated
    is_paid        = db.Column(db.Boolean, default=False)
    isDeleted      = db.Column(db.Boolean, default=False)

    __table_args__ = (
        db.UniqueConstraint(
            "project_id", "account_id", "bill_month",
            name="uq_utility_bill_project_acct_month",
        ),
    )


# ── Utility Forecast ──────────────────────────────────────────────────────────

class UtilityForecast(BaseModel):
    """
    uBillForecast™ output — one row per (project_id, forecast_month).

    Generated by the utility_forecast_engine from trailing bill data,
    CBI trends, and rate projections.

    Forecast horizons: next_month, next_quarter, next_year
    """
    __tablename__ = "utility_forecasts"

    project_id     = db.Column(db.Integer, db.ForeignKey("project.id"),
                               nullable=False, index=True)
    site_id        = db.Column(db.Integer, db.ForeignKey("site.id"),
                               nullable=True,  index=True)

    # Which month this forecast is FOR (YYYY-MM)
    forecast_month = db.Column(db.String(7),  nullable=False, index=True)

    # Forecasted bill components
    forecast_energy_kwh   = db.Column(db.Float, nullable=True)
    forecast_demand_kw    = db.Column(db.Float, nullable=True)
    forecast_energy_cost  = db.Column(db.Float, nullable=True)
    forecast_demand_cost  = db.Column(db.Float, nullable=True)
    forecast_taxes        = db.Column(db.Float, nullable=True)
    forecast_fees         = db.Column(db.Float, nullable=True)
    forecast_total_cost   = db.Column(db.Float, nullable=True)

    # Budget / variance
    budget_total_cost     = db.Column(db.Float, nullable=True)  # if user set a budget
    variance_vs_budget    = db.Column(db.Float, nullable=True)  # forecast - budget ($)
    variance_pct          = db.Column(db.Float, nullable=True)  # %

    # Variance vs prior year same month
    prior_year_total_cost = db.Column(db.Float, nullable=True)
    yoy_variance          = db.Column(db.Float, nullable=True)  # $
    yoy_variance_pct      = db.Column(db.Float, nullable=True)  # %

    # Drivers of change (JSON array of {label, impact_pct, direction})
    drivers_of_change     = db.Column(db.JSON, nullable=True)

    # Rates used for this forecast
    energy_rate           = db.Column(db.Float, nullable=True)
    demand_rate           = db.Column(db.Float, nullable=True)

    # Forecast metadata
    calculated_at         = db.Column(db.BigInteger, nullable=True)
    trailing_months_used  = db.Column(db.Integer, nullable=True)  # how many bills averaged
    confidence            = db.Column(db.String(10), nullable=True)  # "high" | "medium" | "low"
    isDeleted             = db.Column(db.Boolean, default=False)

    __table_args__ = (
        db.UniqueConstraint(
            "project_id", "forecast_month",
            name="uq_utility_forecast_project_month",
        ),
    )
