module.exports = sails.config.constants.buildUpdateAction('gateway', {

  before: function(inputs, proceed) {
    if (inputs.valuesToSet.deviceId) {
      Gateway.find({deviceId: inputs.valuesToSet.deviceId.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, gateways) {
        if (err) { return proceed(err); }
        if (gateways.length) {
          var conflictErr = new Error('A gateway already exists with this device ID');
          conflictErr.exit='conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    } else if(inputs.valuesToSet.name){
      Gateway.find({deviceId: inputs.valuesToSet.name.trim(), id: {'!=': inputs.id}, isDeleted: false}).exec(function(err, gateways) {
        if (err) { return proceed(err); }
        if (gateways.length) {
          var conflictErr = new Error('A gateway already exists with this device ID');
          conflictErr.exit='conflict';
          return proceed(conflictErr);
        }
        return proceed();
      });
    }

  },

  after: function(updatedGateway, exits) {

    // See if there is any PiBoard recorded with the new Gateway's Pi-board serial #.
    PiBoard.findOne({
      deviceId: updatedGateway.deviceId
    }).exec(function(err, piBoard) {
      if (err) {
        return exits.error(err);
      }

      // If not, then the gateway is not online yet (this should be the norm), so we'll just return
      // through the `success` exit generated by `buildCreateAction`.
      if (!piBoard) {
        return exits.success({
          response: {
            id: updatedGateway.id
          }
        });
      }

      // If so, first update the new gateway with the PiBoard's mesh ID.
      Gateway.update({
        id: updatedGateway.id
      }, {
        meshId: piBoard.meshId,
        softwareVersion: piBoard.softwareVersion
      }).exec(function(err) {
        if (err) {
          return exits.error(err);
        }
        return exits.success({
          response: {
            id: updatedGateway.id
          }
        });
      });

    });
  }
});

